/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'IWeui:homeFilled': typeof import('~icons/weui/home-filled')['default']
    'IWeui:settingFilled': typeof import('~icons/weui/setting-filled')['default']
    'IWeui:settingOutlined': typeof import('~icons/weui/setting-outlined')['default']
  }
}
